import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useSession } from "next-auth/react"

export default function Component() {
  const { data: session, status } = useSession()
  if (session && status == "authenticated") {
    return (
      <div className={styles.container}>
        <Head>
          <title>Produto exemplo</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <h1 className={styles.title}>
            {"|"}<a href="#">Produto</a>{"|"}
          </h1>
          <p className={styles.description}>
            Valor: R$ 0.00<br /><br />
            <a href="#"><code className={styles.code}>Adicionar item ao carrinho</code></a><br />
            <a href="#"><code className={styles.code}>Comprar</code></a><br />
            <a href="/"><code className={styles.code}>Voltar</code></a>
          </p>
        </main>
        <footer className={styles.footer}>
          <a
            href="/"
            target="_blank"
            rel="noopener noreferrer"
          >
            Conectado
          </a>
        </footer>
      </div>
    )
  } else if (status == "loading") {
    return (
      <div className={styles.container}>
        <Head>
          <title>Carregando...</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <h1 className={styles.title}>
            {"|"}<a href="#">Carregando...</a>{"|"}
          </h1>
          <p className={styles.description}>
            Carregando...<br /><br />
            <a href="#"><code className={styles.code}>Carregando...</code></a>
          </p>
        </main>
        <footer className={styles.footer}>
          <a
            href="#"
            target="_blank"
            rel="noopener noreferrer"
          >
            Carregando...
          </a>
        </footer>
      </div>
    )
  } else {
    return (
      <div className={styles.container}>
        <Head>
          <title>Produto exemplo</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <h1 className={styles.title}>
            {"|"}<a href="#">Produto</a>{"|"}
          </h1>
          <p className={styles.description}>
            Valor: R$ 0.00<br /><br />
            <a href="/"><code className={styles.code}>Entre com uma conta para comprar</code></a>
          </p>
        </main>
        <footer className={styles.footer}>
          <a
            href="/"
            target="_blank"
            rel="noopener noreferrer"
          >
            Não conectado
          </a>
        </footer>
      </div>
    )
  }

}